### ISSUE TITLE
What's the procedure to do to generate the pre-processd dataset？

### ISSUE THREAD

**Issue by cpuxzb** [mundher/local-global#1]
Is there any code for process the LUNA16 dataset to generate the pre-processd dataset？
What‘s the idea in the procedure？From the original dataset to the pre-processd dataset，What did you do？

**Comment by mundher** [comment]
I explained the full procedure in this paper https://ieeexplore.ieee.org/document/8930524 except here I haven't applied the mask. I discussed the differences in this paper https://arxiv.org/ftp/arxiv/papers/1904/1904.10126.pdf
