### ISSUE TITLE
lidc_img

### ISSUE THREAD

**Issue by cpuxzb** [mundher/local-global#3]

**Comment by cpuxzb** [comment]
1.The dataset is from lidc-irdi,the lidc_img.zip has ten folders,what's the diferences of the ten folders?
2.Data Augmentation:you obtained 15 different images altogether of each nodule through the data augmentation procedure.But,there are 17 images for every 848 nodules？Why？

**Comment by mundher** [comment]
> 1.The dataset is from lidc-irdi,the lidc_img.zip has ten folders,what's the diferences of the ten folders?

All folders contain the same images. However, in every fold the training and the validation set are changing and stored in labels.csv.


>  2.Data Augmentation:you obtained 15 different images altogether of each nodule through the data augmentation procedure.But,there are 17 images for every 848 nodules？Why？

for every nodule, we have 18 images. check Augmenter class in preprocessing.py to understand how these images are generated
