### ISSUE TITLE
Seriesuid/studyuid of preprocessed data

### ISSUE THREAD

**Issue by baltatzisv** [mundher/local-global#4]
Thank you for making your version of the LIDC data available. I am trying to link your data back to the LIDC. Is there a correspondence between the preprocessed data and the indexing used in LIDC? Is the seriesuid or the studyuid of the preprocessed data available? Thank you.

**Comment by mundher** [comment]
I haven't stored the studyuid when I processed the LIDC-IDRI dataset. However, you can regenerate the preprocessed data from LIDC-IDRI using LIDC.py.
You need to change a few lines and store the seriesuid in the lables.csv

**Comment by mundher** [comment]
Apparently, I uploaded the wrong dataset. I just uploaded another dataset without applying masks
